version: '3.0'
services:
  backend:
    build:
      context: /var/lib/jenkins/workspace/Pipeline-Project/server
    container_name: backend
    command: npm start
    ports:
      - 90:8000/tcp
    network_mode: host
    tty: true
    volumes:
      - /var/lib/jenkins/workspace/Pipeline-Project/server:/var/lib/jenkins/workspace/Pipeline-Project:rw
      - /var/lib/jenkins/workspace/Pipeline-Project/server/node_modules
    working_dir: /var/lib/jenkins/workspace/Pipeline-Project

  frontend:
    build:
      context: /var/lib/jenkins/workspace/Pipeline-Project/client
    container_name: frontend
    command: npm start
    ports:
      - 80:5000/tcp
    network_mode: host
    tty: true
    volumes:
      - /var/lib/jenkins/workspace/Pipeline-Project/client:/var/lib/jenkins/workspace/Pipeline-Project:rw
      - /var/lib/jenkins/workspace/Pipeline-Project/client/node_modules
    working_dir: /var/lib/jenkins/workspace/Pipeline-Project
